name: Version Management

on:
  push:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Export Vertex Environment value if main branch
        run: |
          echo "VERTEX_ENV=prod" >> $GITHUB_ENV
        if: ${{github.ref_name == 'main' }}

      - name: Export Vertex Environment value if main branch
        run: |
          echo "VERTEX_ENV=${{github.ref_name}}" >> $GITHUB_ENV
        if: ${{github.ref_name != 'main' }}

      - name: Get the last tag related to branch (environment)
        run: |
          echo "PARSED_TAG=$(git tag | grep prod- | sort | tail -n 1  | sed 's/prod-//')" >> $GITHUB_ENV

      # - name: Bump version and push tag
      #   id: bump_version
      #   uses: anothrNick/github-tag-action@1.36.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: false
      #     VERBOSE: true
      #     DRY_RUN: true
      #     DEFAULT_BUMP: patch
      #     TAG_CONTEXT: branch
      #     INITIAL_VERSION: ${{ env.PARSED_TAG }}
      #     RELEASE_BRANCHES: ${{ github.ref_name }}

      # - name: Bump version and push tag2
      #   id: bump_version2
      #   uses: anothrNick/github-tag-action@1.36.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     VERBOSE: true
      #     DRY_RUN: false
      #     DEFAULT_BUMP: patch
      #     TAG_CONTEXT: branch
      #     CUSTOM_TAG: ${{ env.VERTEX_ENV }}-${{ steps.bump_version.outputs.new_tag }}
      #     # INITIAL_VERSION: ${{ env.VERTEX_ENV }}-${{ steps.bump_version.outputs.new_tag }}
      #     RELEASE_BRANCHES: ${{github.ref_name}}

      # - name: Bump version and push tag2
      #   uses: mathieudutour/github-tag-action@v6.0
      #   id: bump_version2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     release_branches: ${{github.ref_name}}
      #     tag_prefix: ${{ env.VERTEX_ENV }}-

      - uses: butlerlogic/action-autotag@1.0.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          regex_pattern: prod-\d\.\d\.\d


      # - name: Create a GitHub release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.bump_version2.outputs.new_tag }}
      #     release_name: Release ${{ steps.bump_version2.outputs.new_tag }}
