# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # my_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: sleep_command
  #       run: sleep 10
  #     - uses: actions/checkout@master


  my_job2:
    runs-on: ubuntu-latest
    container:
      image: expcmetana/practice:12
      env:
        NODE_ENV: development
        K8S_ENV: EKS
    steps:
      - name: print_env
        run: env



      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

      # # ls -ahl
      # - name: ls
      #   run: ls

      # - name: Checkout tools repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: AntonYanchuk/opswork-test
      #     path: my-tools

      # # Apt install tree.
      # - name: tree
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install tree

      # # tree
      # - name: tree
      #   run: tree
      # # sleep

      # - name: sleep
      #   run: sleep 300


#       - name: sleep
#         run: |
#           runtime="5 minute"
#           endtime=$(date -ud "$runtime" +%s)

#           while [[ $(date -u +%s) -le $endtime ]]
#           do
#               echo "Time Now: `date +%H:%M:%S`"
#               echo "Sleeping for 10 seconds"
# #               sleep 10
# #           done
#   checkout:
#     # The type of runner that the job will run on
#     runs-on: self-hosted

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#         with:
#           repository: AntonYanchuk/Zabbix-ELK
#           path: Zabbix-ELK

#       # Apt install tree.
#       - name: tree
#         run: |
#           sudo apt-get update
#           sudo apt-get install tree

#       # tree
#       - name: tree
#         run: tree

#       # sleep
#       - name: sleep
#         run: |
#           runtime="5 minute"
#           endtime=$(date -ud "$runtime" +%s)

#           while [[ $(date -u +%s) -le $endtime ]]
#           do
#               echo "Time Now: `date +%H:%M:%S`"
#               echo "Sleeping for 10 seconds"
#               sleep 10
#           done
